### ISSUE TITLE
Change de identifier of User

### ISSUE THREAD

**Issue by dhsananias** [rrpadilla/laravel-adminlte-boilerplate#1]
How do I change the authentication, instead of using the email as identifier for the user I would use a table called login, for example.

**Comment by rrpadilla** [comment]
Hi @hananiamizrahi,
you can update your User model table [here](https://github.com/rrpadilla/laravel-adminlte-boilerplate/blob/master/app/User.php#L15):
```php
protected $table = 'login';
```

You can use other unique field Instead of using the email as identifier for the user.
Add the following method to the [LoginController](https://github.com/rrpadilla/laravel-adminlte-boilerplate/blob/master/app/Http/Controllers/Auth/LoginController.php#L22) and replace **'email'** with the field you want to use.
```php
public function username()
{
    return 'email'; // return 'username';
}
```
