### ISSUE TITLE
Can it be updated to adminlte 3.0?

### ISSUE THREAD

**Issue by Vladeeno** [rrpadilla/laravel-adminlte-boilerplate#5]
I saw that the new adminlte is out and it looks nicer then the 2.4.
If I install the current boilerplate how can I upgrade to adminlte 3.0 ?

**Comment by rrpadilla** [comment]
Hi Vladeeno,
because adminlte 3.0 is using bootstrap 4.0 you have to update the template
and every view (forms, tables, etc).
You can add a new directory under [public](
https://github.com/rrpadilla/laravel-adminlte-boilerplate/tree/master/public)
"adminlte-3.0" and copy the new css, js, images and plugins.

Thanks.

**Comment by Vladeeno** [comment]
Hi @rrpadilla 
That was my first thought. I hoped there would be an easier and faster way of doing this.

Thank You

**Comment by rrpadilla** [comment]
Hi Vladeeno,
that's the only way. And we should create a new tag/branch for this.

Thanks.
